export function helpText(): string {
  return [
    "Orchestratory 0.1.0 — security-first local agent workflow",
    "",
    "Usage:",
    "  orchestrator                         Start natural-language TUI + local GUI",
    "  orchestrator tui                     Start terminal-only natural-language mode",
    "  orchestrator gui [--port <number>]   Start the loopback-only visual GUI",
    "  orchestrator web [--port <number>]   Alias for orchestrator gui",
    "  orchestrator mcp [--actor <id>]      Serve collaboration control-plane tools over stdio MCP",
    "  orchestrator run                     Read one workflow JSON from stdin and emit JSONL",
    "  orchestrator doctor                  Check local CLI versions without model calls",
    "  orchestrator models list <provider> [--api]",
    "  orchestrator room init|list|status|writers|audit|pause|resume|off|tail [--follow]|export|log",
    "  orchestrator room hooks --provider <codex|claude|grok> [--install]  # preview by default",
    "  orchestrator room pty codex|grok [--room <id>]    (macOS; owner opt-in + read-only capture)",
    "  MCP Room seat: ask the current agent to call room_join_request directly (never a shell command)",
    "  orchestrator daemon install|uninstall|status   (GUI as login service)",
    "  orchestrator workspaces list|allow <path> [--label <name>]",
    "  orchestrator worktrees list|cleanup <run-id> [--execute]",
    "  orchestrator candidates orphan-refs <workspace>   # read-only; lists, never deletes",
    "  orchestrator candidates promotions <workspace>    # re-observes and updates unsettled records",
    "  orchestrator candidates promotions <workspace> release <promotion-id> --confirm <phrase> [--pid N] [--pgid N]",
    "                                                    # stops this record waiting; kills nothing, never writes main",
    "  orchestrator data inventory|integrity|purge [--execute]",
    "  orchestrator data retention show|set [--terminal-days N] [--max-runs N]",
    "  orchestrator telemetry status|on|off|log   # anonymous daily summary; off until you answer",
    "  orchestrator config show",
    "  orchestrator audit",
    "",
    "Destructive, billed, worktree, test and restore actions remain approval-gated.",
    "",
    "ORCHESTRATORY_DATA_DIR overrides where every store lives. Development against a working tree",
    "shares one database with the installed runtime otherwise, and the first migration by the newer",
    "of the two locks the older out of it. Set it to a directory you own, mode 0700 -- an existing one",
    "that is not, or that belongs to somebody else, is named and refused; an invalid value is refused",
    "rather than silently ignored. `orchestrator data inventory` prints the path in use and where it",
    "came from.",
    "",
    "A worktree is a record and a recovery point, not an OS sandbox: a full-trust agent running under",
    "your own account can bypass an application-level boundary. Use a container or a separate account",
    "if you need enforced isolation.",
    "",
  ].join("\n");
}
