export function helpText(): string {
  return [
    "Orchestratory 0.1.0 — security-first local agent workflow",
    "",
    "Usage:",
    "  orchestrator                         Start natural-language TUI + local GUI",
    "  orchestrator tui                     Start terminal-only natural-language mode",
    "  orchestrator gui [--port <number>]   Start the loopback-only visual GUI",
    "  orchestrator web [--port <number>]   Alias for orchestrator gui",
    "  orchestrator mcp [--actor <id>]      Serve read-only collaboration tools over stdio MCP",
    "  orchestrator run                     Read one workflow JSON from stdin and emit JSONL",
    "  orchestrator doctor                  Check local CLI versions without model calls",
    "  orchestrator models list <provider> [--api]",
    "  orchestrator room init|list|status|writers|audit|pause|resume|off|tail [--follow]|export|log",
    "  orchestrator room hooks --provider <codex|claude|grok> [--install]  # preview by default",
    "  orchestrator room pty codex|grok [--room <id>]    (macOS; owner opt-in + read-only capture)",
    "  MCP Room seat: ask the current agent to call room_join_request directly (never a shell command)",
    "  orchestrator daemon install|uninstall|status   (GUI as login service)",
    "  orchestrator workspaces list|allow <path> [--label <name>]",
    "  orchestrator worktrees list|cleanup <run-id> [--execute]",
    "  orchestrator data inventory|integrity|purge [--execute]",
    "  orchestrator data retention show|set [--terminal-days N] [--max-runs N]",
    "  orchestrator config show",
    "  orchestrator audit",
    "",
    "Destructive, billed, worktree, test and restore actions remain approval-gated.",
    "",
  ].join("\n");
}
